## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Reading Dataset

In [2]:
df = pd.read_csv("C:\\Users\\Nagasai\\Downloads\\winequality-red.csv")
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [3]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

## Finding the null values

In [4]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

## Seperating Input and output variables

In [5]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [6]:
X

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [7]:
y

array([5, 5, 5, ..., 6, 5, 6], dtype=int64)

## Splitting training and test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [9]:
X_train

array([[ 7.6 ,  0.36,  0.31, ...,  3.46,  0.62,  9.5 ],
       [12.2 ,  0.45,  0.49, ...,  3.13,  0.63, 10.4 ],
       [12.  ,  0.38,  0.56, ...,  3.14,  0.71, 10.9 ],
       ...,
       [ 8.4 ,  0.36,  0.32, ...,  3.3 ,  0.72, 11.  ],
       [ 9.7 ,  0.69,  0.32, ...,  3.29,  0.62, 10.1 ],
       [ 8.7 ,  0.42,  0.45, ...,  3.33,  0.77, 12.  ]])

In [10]:
y_train

array([6, 5, 6, ..., 6, 5, 6], dtype=int64)

In [11]:
y_test

array([5, 5, 6, 6, 6, 7, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 6, 6, 5, 6, 7,
       5, 6, 6, 5, 6, 5, 5, 5, 8, 5, 6, 7, 5, 7, 6, 7, 6, 5, 5, 5, 5, 5,
       6, 7, 5, 5, 7, 6, 5, 6, 7, 5, 5, 4, 6, 5, 4, 6, 5, 5, 5, 6, 7, 6,
       6, 6, 4, 7, 6, 5, 5, 5, 6, 5, 5, 6, 5, 7, 5, 5, 7, 7, 6, 5, 6, 6,
       6, 7, 5, 7, 5, 6, 5, 5, 5, 7, 5, 6, 5, 6, 6, 7, 5, 6, 6, 5, 7, 6,
       7, 7, 7, 5, 4, 7, 6, 6, 5, 8, 5, 7, 7, 7, 6, 5, 5, 6, 6, 6, 6, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 6, 7, 6, 5, 5, 5, 5, 6, 5, 5, 5, 6,
       7, 4, 6, 7, 5, 7, 5, 5, 7, 5, 5, 5, 5, 7, 6, 5, 8, 5, 5, 6, 6, 4,
       6, 5, 5, 5, 4, 6, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 7, 5, 7, 6, 4,
       6, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 5, 8, 6, 6, 7, 5, 6,
       5, 6, 5, 5, 6, 5, 6, 7, 6, 5, 5, 6, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5,
       5, 5, 7, 5, 5, 6, 6, 6, 6, 7, 6, 6, 6, 6, 5, 7, 6, 5, 5, 5, 5, 6,
       5, 6, 6, 5, 6, 6, 6, 6, 7, 6, 5, 6, 5, 7, 5, 6, 5, 7, 7, 5, 5, 6,
       6, 5, 5, 6, 4, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6,

In [12]:
X_test

array([[10.8  ,  0.45 ,  0.33 , ...,  3.24 ,  0.71 , 10.8  ],
       [ 9.   ,  0.58 ,  0.25 , ...,  3.27 ,  0.72 ,  9.6  ],
       [ 7.2  ,  0.38 ,  0.3  , ...,  3.42 ,  0.59 ,  9.5  ],
       ...,
       [ 8.8  ,  0.4  ,  0.4  , ...,  3.44 ,  0.64 ,  9.2  ],
       [11.9  ,  0.695,  0.53 , ...,  3.17 ,  0.84 , 12.2  ],
       [ 7.2  ,  0.655,  0.03 , ...,  3.34 ,  0.39 ,  9.5  ]])

## Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train

array([[-0.40314494, -0.92671379,  0.21255498, ...,  0.94530029,
        -0.22533623, -0.8690753 ],
       [ 2.25470239, -0.42900453,  1.13864145, ..., -1.19138312,
        -0.16782176, -0.01547374],
       [ 2.13914381, -0.81611173,  1.49878618, ..., -1.12663514,
         0.29229406,  0.45874935],
       ...,
       [ 0.05908938, -0.92671379,  0.26400423, ..., -0.09066742,
         0.34980854,  0.55359397],
       [ 0.81022014,  0.89822014,  0.26400423, ..., -0.15541541,
        -0.22533623, -0.30000759],
       [ 0.23242725, -0.59490762,  0.93284445, ...,  0.10357652,
         0.63738092,  1.50204014]])

## Principal Component Analysis

In [15]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 5)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

## Training LinearRegression Model

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [17]:
y_pred = regressor.predict(X_test)
y_pred

array([5.79611743, 5.38025733, 5.47753294, 6.24055707, 5.35243112,
       6.41084901, 5.4484392 , 5.21601017, 5.48323904, 6.08461458,
       4.99034021, 5.08115019, 5.40712503, 5.41139006, 5.83680697,
       5.93575059, 5.25063029, 5.49203685, 5.68899228, 5.50529667,
       5.7999758 , 6.08390013, 5.63992665, 5.31815478, 5.15082063,
       5.42121474, 5.00498644, 5.53022759, 4.87741052, 5.10700567,
       6.17434514, 5.46303475, 6.40480797, 6.58741057, 5.66119195,
       6.57511572, 5.3914344 , 5.61776587, 5.13580156, 5.45743366,
       5.49054559, 5.32541088, 5.12621401, 5.47449261, 5.670854  ,
       6.34111335, 5.30800706, 5.51787935, 6.61098526, 6.02036264,
       5.62428995, 5.74426683, 6.41904152, 5.51217638, 5.07224573,
       5.73217715, 4.97050983, 5.06593703, 5.6215751 , 5.31075025,
       5.46849923, 5.7402899 , 5.20819626, 5.07314328, 5.75295313,
       5.07314328, 6.20278039, 6.04436844, 5.40966745, 6.5362109 ,
       5.48423441, 6.08606702, 4.97784406, 6.27098488, 6.25381

## Evaluating performance

In [18]:
from sklearn.metrics import r2_score
print(r2_score(y_test, regressor.predict(X_test)))

0.3369521464251424


## Cross Validation

In [19]:
from sklearn.model_selection import cross_val_score
cross_val_score(regressor,X,y,scoring = 'r2',cv = 5)

array([0.13200871, 0.31858135, 0.34955348, 0.369145  , 0.2809196 ])