## Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Reading the Dataset

In [2]:
df = pd.read_csv("C:\\Users\\Nagasai\\Downloads\\Real estate.csv")
df

No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 8 columns]

In [3]:
df.describe()

No  X1 transaction date  X2 house age  \
count  414.000000           414.000000    414.000000   
mean   207.500000          2013.148971     17.712560   
std    119.655756             0.281967     11.392485   
min      1.000000          2012.667000      0.000000   
25%    104.250000          2012.917000      9.025000   
50%    207.500000          2013.167000     16.100000   
75%    310.750000          2013.417000     28.150000   
max    414.000000          2013.583000     43.800000   

       X3 distance to the nearest MRT station  \
count                              414.000000   
mean                              1083.885689   
std                               1262.109595   
min                                 23.382840   
25%                                289.324800   
50%                                492.231300   
75%                               1454.279000   
max                               6488.021000   

       X4 number of convenience stores  X5 latitude  X6 longitude  \
count                       414.000000   414.000000    414.000000   
mean                          4.094203    24.969030    121.533361   
std                           2.945562     0.012410      0.015347   
min                           0.000000    24.932070    121.473530   
25%                           1.000000    24.963000    121.528085   
50%                           4.000000    24.971100    121.538630   
75%                           6.000000    24.977455    121.543305   
max                          10.000000    25.014590    121.566270   

       Y house price of unit area  
count                  414.000000  
mean                    37.980193  
std                     13.606488  
min                      7.600000  
25%                     27.700000  
50%                     38.450000  
75%                     46.600000  
max                    117.500000

In [4]:
df.isnull().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

## Dividiing dependent and independent variables

In [5]:
X = df.iloc[:,2:-1].values
y = df.iloc[:,-1].values

In [6]:
X

array([[ 32.     ,  84.87882,  10.     ,  24.98298, 121.54024],
       [ 19.5    , 306.5947 ,   9.     ,  24.98034, 121.53951],
       [ 13.3    , 561.9845 ,   5.     ,  24.98746, 121.54391],
       ...,
       [ 18.8    , 390.9696 ,   7.     ,  24.97923, 121.53986],
       [  8.1    , 104.8101 ,   5.     ,  24.96674, 121.54067],
       [  6.5    ,  90.45606,   9.     ,  24.97433, 121.5431 ]])

In [7]:
y

array([ 37.9,  42.2,  47.3,  54.8,  43.1,  32.1,  40.3,  46.7,  18.8,
        22.1,  41.4,  58.1,  39.3,  23.8,  34.3,  50.5,  70.1,  37.4,
        42.3,  47.7,  29.3,  51.6,  24.6,  47.9,  38.8,  27. ,  56.2,
        33.6,  47. ,  57.1,  22.1,  25. ,  34.2,  49.3,  55.1,  27.3,
        22.9,  25.3,  47.7,  46.2,  15.9,  18.2,  34.7,  34.1,  53.9,
        38.3,  42. ,  61.5,  13.4,  13.2,  44.2,  20.7,  27. ,  38.9,
        51.7,  13.7,  41.9,  53.5,  22.6,  42.4,  21.3,  63.2,  27.7,
        55. ,  25.3,  44.3,  50.7,  56.8,  36.2,  42. ,  59. ,  40.8,
        36.3,  20. ,  54.4,  29.5,  36.8,  25.6,  29.8,  26.5,  40.3,
        36.8,  48.1,  17.7,  43.7,  50.8,  27. ,  18.3,  48. ,  25.3,
        45.4,  43.2,  21.8,  16.1,  41. ,  51.8,  59.5,  34.6,  51. ,
        62.2,  38.2,  32.9,  54.4,  45.7,  30.5,  71. ,  47.1,  26.6,
        34.1,  28.4,  51.6,  39.4,  23.1,   7.6,  53.3,  46.4,  12.2,
        13. ,  30.6,  59.6,  31.3,  48. ,  32.5,  45.5,  57.4,  48.6,
        62.9,  55. ,

## Splitting train and test set

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size =0.2, random_state = 1)

In [33]:
X_test

array([[1.0400000e+01, 2.2519380e+03, 4.0000000e+00, 2.4959570e+01,
        1.2151353e+02],
       [1.1000000e+00, 1.9358450e+02, 6.0000000e+00, 2.4965710e+01,
        1.2154089e+02],
       [8.9000000e+00, 3.0781760e+03, 0.0000000e+00, 2.4954640e+01,
        1.2156627e+02],
       [1.6000000e+01, 4.0665870e+03, 0.0000000e+00, 2.4942970e+01,
        1.2150342e+02],
       [0.0000000e+00, 2.7401440e+02, 1.0000000e+00, 2.4974800e+01,
        1.2153059e+02],
       [1.4700000e+01, 1.7171930e+03, 2.0000000e+00, 2.4964470e+01,
        1.2151649e+02],
       [1.8200000e+01, 2.1795900e+03, 3.0000000e+00, 2.4962990e+01,
        1.2151252e+02],
       [1.3100000e+01, 1.1648380e+03, 4.0000000e+00, 2.4991560e+01,
        1.2153406e+02],
       [1.7700000e+01, 3.5085150e+02, 1.0000000e+00, 2.4975440e+01,
        1.2153119e+02],
       [3.0300000e+01, 4.5103590e+03, 1.0000000e+00, 2.4949250e+01,
        1.2149542e+02],
       [2.7100000e+01, 4.4127650e+03, 1.0000000e+00, 2.4950320e+01,
        1.21

In [34]:
X_test

array([[1.0400000e+01, 2.2519380e+03, 4.0000000e+00, 2.4959570e+01,
        1.2151353e+02],
       [1.1000000e+00, 1.9358450e+02, 6.0000000e+00, 2.4965710e+01,
        1.2154089e+02],
       [8.9000000e+00, 3.0781760e+03, 0.0000000e+00, 2.4954640e+01,
        1.2156627e+02],
       [1.6000000e+01, 4.0665870e+03, 0.0000000e+00, 2.4942970e+01,
        1.2150342e+02],
       [0.0000000e+00, 2.7401440e+02, 1.0000000e+00, 2.4974800e+01,
        1.2153059e+02],
       [1.4700000e+01, 1.7171930e+03, 2.0000000e+00, 2.4964470e+01,
        1.2151649e+02],
       [1.8200000e+01, 2.1795900e+03, 3.0000000e+00, 2.4962990e+01,
        1.2151252e+02],
       [1.3100000e+01, 1.1648380e+03, 4.0000000e+00, 2.4991560e+01,
        1.2153406e+02],
       [1.7700000e+01, 3.5085150e+02, 1.0000000e+00, 2.4975440e+01,
        1.2153119e+02],
       [3.0300000e+01, 4.5103590e+03, 1.0000000e+00, 2.4949250e+01,
        1.2149542e+02],
       [2.7100000e+01, 4.4127650e+03, 1.0000000e+00, 2.4950320e+01,
        1.21

In [35]:
y_train

array([ 37.4,  51.8,  58.1,  49.5,  30.6,  48. ,  18.2,  27.7,  69.7,
        67.7,  26.6,  47.9,  42.2,  23.8,  40.5,  63.2,  55.2,  46.6,
        46.2,  24.4,  21.5,  43.1,  43.8,  55. ,  28.6,  35.1,  54.4,
        78. ,  58. ,  46.1, 117.5,  25.7,  48.1,  53.3,  42.3,  33.6,
        25.3,  42.5,  20. ,  40.6,  29.3,  33.1,  41. ,  26.5,  51. ,
        42. ,  37.4,  43.2,  58.8,  40.1,  41.6,  48.6,  42.4,  31.3,
        39.3,  36.7,  63.9,  23.5,  15.6,  22.8,  13.8,  51.7,  60.7,
        48. ,  30.7,  57.4,  63.3,  34.3,  45.2,  45.5,  43.5,  39.4,
        20.7,  23.1,  22.1,  30.7,  70.1,  48.2,  37.9,  71. ,  12.9,
        40.2,  31.3,  59. ,  47.7,  48.5,  46. ,  55.5,  43.4,  24.7,
        26.2,  31.3,  45.5,  45.9,  34.7,  57.8,  62.1,  19. ,  61.9,
        48.5,  40.5,  32.9,  46.6,  34.1,  24.7,  43.2,  35.5,  38.2,
        55.1,  44.3,  51.6,  36.5,  38.9,  20.8,  25.6,  20.7,  47.7,
        37.5,  39.4,  34.4,  53.9,  30.1,  40.6,  31.3,  34.1,  45.1,
        23.5,  26.5,

In [36]:
y_test

array([27.3, 54.4, 22. , 11.6, 45.4, 23. , 21.8, 32.2, 37.4, 22.6, 17.4,
       36.8, 23.1, 36.9, 56.3, 20.9, 43.5, 40.3, 27.7, 42.1, 46.6, 21.8,
       38.1, 53.7, 57.1, 26.6, 32.1, 56.8, 43.1, 16.7, 33.4, 34.2, 39.6,
       52.5, 47.1, 13. , 37.5, 32.5, 42.3, 20.5, 40.3, 16.1, 58.1, 33.4,
       30.8, 21.7, 20.9, 42.5, 38.1, 39.6, 18.6, 44.3, 39.7, 15.4, 50.8,
       36.3, 52.2, 37.8, 26.5, 42.5, 12.8, 32.9, 29.4, 19.2, 42.6, 32.4,
       42.7, 42.3, 15.9, 43.9, 44.5, 15.5, 29.8, 24.5, 50. , 37.2, 30.9,
       37. , 33.1, 59.6, 40.8, 52.2, 47.1])

## Standardization

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [38]:
X

array([[ 32.     ,  84.87882,  10.     ,  24.98298, 121.54024],
       [ 19.5    , 306.5947 ,   9.     ,  24.98034, 121.53951],
       [ 13.3    , 561.9845 ,   5.     ,  24.98746, 121.54391],
       ...,
       [ 18.8    , 390.9696 ,   7.     ,  24.97923, 121.53986],
       [  8.1    , 104.8101 ,   5.     ,  24.96674, 121.54067],
       [  6.5    ,  90.45606,   9.     ,  24.97433, 121.5431 ]])

## Training Linear Regression Model

In [39]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [40]:
y_pred = regressor.predict(X_test)

In [41]:
y_pred

array([33.07996225, 47.80869225, 22.11373816, 15.13096266, 44.6259416 ,
       33.34343735, 31.19940423, 44.33327931, 39.97905651, 12.34608693,
       13.8395669 , 39.23834498, 30.78835143, 45.73299058, 52.39244171,
       34.0245196 , 44.6259416 , 43.13136871, 31.475026  , 46.30046212,
       52.58815104, 29.97317982, 40.69807579, 48.86155195, 46.10788025,
       28.72708906, 34.00302145, 45.51555296, 47.95300422, 14.53618299,
       35.830845  , 35.24661163, 40.78115048, 45.61532743, 48.63792301,
       14.1309192 , 41.07859656, 40.65344242, 38.5988199 , 15.05613181,
       41.92880337, 25.42152773, 52.21783639, 34.88185988, 33.64942531,
       39.47780571, 32.82670042, 41.10007362, 44.07963274, 34.27966577,
       14.15586281, 43.05867842, 48.10381014, 15.2844915 , 51.29462089,
       43.87893238, 44.6259416 , 39.2943165 , 40.7370706 , 42.33569508,
       25.39313138, 41.71660439, 33.97016178, 14.1309192 , 40.50311433,
       44.32122364, 39.34067446, 45.5714346 , 15.30943512, 39.67

## Metrics

In [42]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_error
print(f'R2 Score :{r2_score(y_test, y_pred)}')
print(f'Mean Squared error :{mean_squared_error(y_test, y_pred)}')
print(f'Mean absolute error :{mean_absolute_error(y_test, y_pred)}')

R2 Score :0.700731455305317
Mean Squared error :45.424791224618865
Mean absolute error :5.380155144270497


In [43]:
from sklearn.model_selection import cross_val_score
cross_val_score(regressor,X,y,scoring = 'r2',cv = 15)

array([0.59022727, 0.68671616, 0.74412483, 0.71039704, 0.36764481,
       0.48052924, 0.7997755 , 0.43169893, 0.66452501, 0.24138846,
       0.48497651, 0.5662566 , 0.62665947, 0.58638073, 0.47861859])